gestor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='gestor_index'),
    url(r'^home$', views.index, name='gestor_index'),

    url(r'^cadastro/$',views.cadastroUsuario, name='cadastro_usuario'),
    url(r'^login/$',views.loginSys, name='login'),
    url(r'^logout/$',views.logoutSys, name='logout'),

    url(r'^metas_projeto/$',views.metas_projeto, name='metas_projeto'),
    url(r'^(?P<id>[-\w\d]+)/update_meta$', views.update_meta, name='update_meta'),

    url(r'^resultado_estado/$',views.resultado_estado, name='resultado_estado'),

    url(r'^cadastro_noticias/$',views.cadastro_noticias, name='cadastro_noticias'),    
    url(r'^noticias_lista/$',views.noticias_lista, name='noticias_lista'),   
    url(r'^(?P<noticia>[-\w\d]+)/atualizar_noticia/$',views.atualizar_noticia, name='atualizar_noticia'),   
    url(r'^(?P<noticia>[-\w\d]+)/excluir_noticia/$',views.excluir_noticia, name='excluir_noticia'),   
    url(r'^(?P<noticia>[-\w\d]+)/home_noticia/$',views.home_noticia, name='home_noticia'),   

    url(r'^newsletter/$',views.newsletter, name='newsletter'),


    url(r'^noticias/$',views.noticias, name='noticias'),
    url(r'^lista_noticias/$',views.lista_noticias, name='lista_noticias'),
    url(r'^ajax_ista_noticias/$',views.ajax_ista_noticias, name='ajax_ista_noticias'),
    url(r'^ajax_del_noticias/$',views.ajax_del_noticias, name='ajax_del_noticias'),
    url(r'^ajax_capa_noticias/$',views.ajax_capa_noticias, name='ajax_capa_noticias'),


    url(r'^ajax_noticias/$',views.ajax_noticias, name='ajax_noticias'),
    
    url(r'^newsletter/$',views.newsletter_emails, name='newsletter_emails'),

    url(r'^depoimentos/$',views.depoimentos, name='depoimentos'),
    url(r'^depoimento/novo/$',views.novo_depoimento, name='novo_depoimento'),
    url(r'^depoimento/update/(?P<id_depoimento>[-\w\d]+)$',views.update_depoimento, name='update_depoimento'),


    

]

web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='web_home'),
    url(r'^tecnologias/$', views.tecnologias, name='web_tecnologias'),
    url(r'^participe/$', views.participe, name='web_participe'),
    url(r'^resultados_alcancados/$', views.resultados_alcancados, name='resultados_alcancados'),

    url(r'^destaque/$', views.destaque, name='web_destaque'),
    url(r'^destaque/(?P<chave>[-\w\d]+)/$', views.materia, name='web_materia'),
    url(r'^materia/ajax_materia/$', views.ajax_materia, name='web_ajax_materia'),

    url(r'^downloads/$', views.downloads, name='web_downloads'),
    url(r'^sobre/$', views.sobre, name='web_sobre'),
    url(r'^projetoAcoes/$', views.projetoAcoes, name='web_projetoAcoes'),
    url(r'^beneficiario/$', views.beneficiario, name='web_beneficiario'),
    url(r'^instituicao_aprovada/$', views.instituicao_aprovada, name='web_instituicao_aprovada'),

    url(r'^flipbook_doctec_gestao/$', views.flipbook_doctec_gestao, name='web_flipbook_doctec_gestao'),
    url(r'^flipbook_doctec_ilpf/$', views.flipbook_doctec_ilpf, name='web_flipbook_doctec_ilpf'),
    url(r'^flipbook_doctec_rad/$', views.flipbook_doctec_rad, name='web_flipbook_doctec_rad'),
    url(r'^flipbook_doctec_pfc/$', views.flipbook_doctec_pfc, name='web_flipbook_doctec_pfc'),
    url(r'^flipbook_doctec_msfn/$', views.flipbook_doctec_msfn, name='web_flipbook_doctec_msfn'),

    url(r'^informativo/(?P<informativo_flipbook>[-\w\d]+)$', views.informativo_flipbook, name='informativo_flipbook'),

    url(r'^infografico/(?P<infografico>[-\w\d]+)$', views.infografico, name='infografico'),

    url(r'^noticia/(?P<noticia_id>[-\w\d]+)/prs$', views.visualizar_noticia, name='visualizar_noticia'),
    url(r'^destaques/$', views.destaques_lista, name='destaques_lista'),

    url(r'^depoimento/(?P<id_depoimento>[-\w\d]+)/video$', views.video_depoimento, name='video_depoimento'),

    url(r'^videos/(?P<ator>[-\w\d]+)/depoimento$', views.depoimento, name='web_depoimento'),
    url(r'^chamadapiloto/$', views.chamadapiloto, name='web_chamadapiloto'),
    url(r'^chamadaud/$', views.chamadaud, name='web_chamadaud'),
    url(r'^chamada_direcionada/$', views.chamada_direcionada, name='web_chamada_direcionada'),
    url(r'^chamada_um/$', views.chamada_um, name='web_chamada_um'),
    url(r'^mudas_insumos/$', views.mudas_insumos, name='web_mudas_insumos'),

    url(r'^modulofiscal/$', views.modulofiscal, name='web_modulofiscal'),
    url(r'^historiarural/$', views.historiarural, name='web_historiarural'),
    url(r'^resultado/$', views.resultado, name='resultado'),
    url(r'^resultado_ud/$', views.resultado_ud, name='resultado_ud'),
    url(r'^select_resultado/$', views.select_resultado, name='select_resultado'),

    url(r'^janela_conhecimento/$', views.janela_conhecimento, name='janela_conhecimento'),

    url(r'^edital_ud/$', views.edital_ud, name='web_edital_ud'),
    url(r'^edital_um_direcionada/$', views.edital_um_direcionada, name='edital_um_direcionada'),
    url(r'^en/$', views.web_en, name='web_en'),
    url(r'^es/$', views.web_es, name='web_es'),


]

webruralsustentavel/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'', include('web.urls')),
    url(r'gestor/', include('gestor.urls', namespace='gestor', app_name='gestor')),

    url(r'^admin/', include(admin.site.urls)),

]

templates/base/base.html
{% load static %}
<html>
<head>
   <title>Rural Sustentável</title>

   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://s3-sa-east-1.amazonaws.com/ruralsustentavel-cms-teste/site/css/navbar_and_footer.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block base_content_css %}{% endblock %}

    <style>
        .navbar-drop {
            color: #000 !important;
        }
    </style>

    <link rel="shortcut icon" href="https://s3-sa-east-1.amazonaws.com/ruralsustentavel-cms-teste/site/img/image_home/favicon.png" type="image/x-icon" />

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">

            <div class="navbar-header page-scroll">
                <a class="navbar-brand" href="/"><img src="https://s3-sa-east-1.amazonaws.com/ruralsustentavel-cms-teste/site/img/image_home/logo_prs.png"></a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <!-- <li class="page-scroll" style="background-color: #D6B917;">
                        <a href="http://portal.ruralsustentavel.org/instituicao/cadastro/" style="color:#FFF;">Cadastre sua Instituição</a>
                    </li> -->
                    <li class="page-scroll" style="margin-right: 10px;">
                        <a href="/es" style="color:#FFF;">
                            <img src="{% static "site_en/img/bandeira_espanhol.png"%}" style="width: 40px;top: 5px;position: absolute;left: -40px;">
                        </a>
                    </li>
                    <li class="page-scroll" style="margin-right: 10px">
                        <a href="/en" style="color:#FFF;">
                            <img src="{% static "site_en/img/bandeira_ingles.png"%}" style="width: 40px;top: 5px;position: absolute;left: -30px;">
                        </a>
                    </li>
                    <li class="page-scroll" style="background-color: #006B31; margin-right: 10px;">
                    <!-- <li class="page-scroll" style="background-color: #D6B917; margin-right: 10px;"> -->
                        <a href="/resultados_alcancados" style="color: #FFF;">Resultados alcançados <span class="glyphicon glyphicon-tree-deciduous"></span></a>
                    </li>
                    <li class="page-scroll" style="background-color: #D6B917;">
                        <a href="http://portal.ruralsustentavel.org/login/" style="color: #FFF;">Login <span class="glyphicon glyphicon-log-in"></span></a>
                    </li>
                </ul><br><br><br>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll dropdown" >
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">O projeto<span class="caret"></span></a>
                        <ul class="dropdown-menu header">
                          <li><a href="/sobre/" class="navbar-drop">Informações Gerais</a></li>
                          <li><a href="/projetoAcoes/" class="navbar-drop">Ações do Projeto</a></li>
                          <li><a href="/beneficiario/" class="navbar-drop">Produtores e Produtoras Rurais</a></li>
                          <li><a href="/instituicao_aprovada/" class="navbar-drop">Instituição de ATER e ATECs</a></li>
                        </ul>
                    </li>

                    <li class="page-scroll">
                        <a href="/tecnologias">Tecnologias</a>
                    </li>
<!--                     <li class="page-scroll">
                        <a href="#">Historia rural</a>
                    </li> -->
                    <li class="page-scroll">
                        <a href="/participe/">Participe</a>
                    </li>
                    <li class="page-scroll">
                        <a href="/destaques/">Notícias</a>
                    </li>
                    <li class="page-scroll">
                        <!-- <a href="/downloads/">Janela do conhecimento</a> -->
                        <a href="/janela_conhecimento/">Janela do conhecimento</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div style="margin-top: 150px;"></div>
    {% block base_content %}{% endblock %}

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- <img class="img-responsive" src="https://s3-sa-east-1.amazonaws.com/ruralsustentavel-cms-teste/site/img/image_home/Logos-parceiros.png" style="margin-bottom: 50px;"> -->
                        <img class="img-responsive" src="{% static "image/home/roda_pe.png"%}" style="margin-bottom: 50px;">
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Rural Sustentavel 2017
                    </div>
                </div>
            </div>
        </div>
    </footer>


</body>
</html

templates/base/base_gestor.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://s3.amazonaws.com/ruralsustentavel-site/static/css/home_style.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <style>
        a {
            color: #08622E !important;
        }
    </style>

</head>
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <!-- /.navbar-header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/gestor/">
                    <img width="120" src="https://s3-sa-east-1.amazonaws.com/ruralsustentavel-cms-teste/site/img/image_home/logo_prs.png" alt="">
                </a>
            </div>
            <!-- /.navbar-header -->

            <!-- /.navbar-top-links -->
            <ul class="nav navbar-top-links navbar-right">

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{% url 'gestor:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <!-- sidebar collapse -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <!-- <li>
                            <a href="#"><i class="fa fa-dashboard fa-fw"></i> menu 1</a>
                        </li> -->
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> &nbsp;&nbsp;metas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="{% url 'gestor:metas_projeto' %}">&nbsp;Metas do Projeto</a></li>
                                <li><a href="{% url 'gestor:resultado_estado' %}">&nbsp;Resultados por Estado</a></li>
                                <!-- <li><a href="/gestor/metas_geral/">&nbsp;## Metas gerais</a></li>
                                <li><a href="/gestor/metas_estado">&nbsp;## Metas por estados</a></li> -->
                            </ul>
                        </li>
                        <li>
                            <a href="#"><span class="glyphicon glyphicon-send"></span> &nbsp;&nbsp;Notícias <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <!-- <a href="/gestor/noticias/">&nbsp;Nova Notícia</a> -->
                                    <a href="/gestor/cadastro_noticias/">&nbsp;Nova Notícia</a>
                                </li>
                                <li>
                                    <!-- <a href="/gestor/lista_noticias/">&nbsp;Lista de notícias</a> -->
                                    <a href="/gestor/noticias_lista/">&nbsp;Lista de notícias</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="/gestor/newsletter">
                                <span class="glyphicon glyphicon-envelope"></span> &nbsp;&nbsp;E-mails Newsletter
                            </a>
                        </li>
                        <li>
                            
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-edit fa-fw"></i> &nbsp;&nbsp;Depoimentos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="/gestor/depoimentos"> Lista de depoimentos</a></li>
                                <li><a href="/gestor/depoimento/novo"> Novo depoimentos</a></li>
                                <!-- <li><a href="/gestor/metas_geral/">&nbsp;## Metas gerais</a></li>
                                <li><a href="/gestor/metas_estado">&nbsp;## Metas por estados</a></li> -->
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- sidebar collapse -->
        </nav>

        <!-- /#corpo da pagina -->
        <div id="page-wrapper">
            <div style="padding: 20px 0">{% block base_content %}{% endblock %}</div>
            <!-- <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Titulo inicial</h1>
                </div>
            </div> -->
        </div>
        <!-- /#corpo da pagina -->
    </div>
    <!-- /#wrapper -->




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://s3.amazonaws.com/ruralsustentavel-site/static/js/menu_bar.js"></script>
    <script src="https://s3.amazonaws.com/ruralsustentavel-site/static/js/script_main.js"></script>

</body>
</html>

templates/base/base_janela.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="{% static "janelaconhecimento/vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{% static "janelaconhecimento/vendor/font-awesome/css/font-awesome.min.css"%}" rel="stylesheet">
    <link href="{% static "janelaconhecimento/vendor/devicons/css/devicons.min.css"%}" rel="stylesheet">
    <link href="{% static "janelaconhecimento/vendor/simple-line-icons/css/simple-line-icons.css"%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "janelaconhecimento/css/resume.css"%}" rel="stylesheet">

</head>

<body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <!-- <a class="navbar-brand js-scroll-trigger" href="#page-top"> -->
        <a data-toggle="tooltip" data-placement="top" title="Voltar para o Início!" class="navbar-brand js-scroll-trigger" href="/">
            <span class="d-block d-lg-none">Rural Sustentável</span>
            <span class="d-none d-lg-block">
                <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static "janelaconhecimento/img/profile.jpg"%}" alt="">
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#infografico">Infográficos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#publicacao">Documentos Técnicos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#informes">Informes Técnicos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#cartilhas">Cartilhas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#videos">Vídeos <small>(depoimentos)</small> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#janela">Outros Materiais</a>
                </li>
            </ul>
        </div>
    </nav>


    {% block base_content %}{% endblock %}


</body>
</html